FROM php:8.3-fpm

# Instalar dependências
RUN apt-get update && apt-get install -y \
    libonig-dev \
    libxml2-dev \
    zip unzip git curl && \
    docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath

# Composer
COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
